-- 1. CLEAN UP: Remove all existing policies to avoid name conflicts
DROP POLICY IF EXISTS "Enable read for all users" ON inventory;
DROP POLICY IF EXISTS "Enable update for all users" ON inventory;
DROP POLICY IF EXISTS "inventory_public_access" ON inventory;
DROP POLICY IF EXISTS "Enable insert for all users" ON leads;
DROP POLICY IF EXISTS "Enable read for all users" ON leads;
DROP POLICY IF EXISTS "Enable update for all users" ON leads;
DROP POLICY IF EXISTS "Enable delete for all users" ON leads;
DROP POLICY IF EXISTS "leads_public_access" ON leads;

-- 2. ENSURE TABLES EXIST WITH CORRECT COLUMNS

-- Inventory Table (Recreated for per-venue support)
DROP TABLE IF EXISTS inventory;
CREATE TABLE inventory (
  id TEXT NOT NULL,
  venue TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  label TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (id, venue)
);

-- Leads Table (Ensure it exists and has all required columns)
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  venue TEXT NOT NULL,
  prize TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure existing leads table has the new columns if it wasn't recreated
ALTER TABLE leads ADD COLUMN IF NOT EXISTS venue TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS prize TEXT DEFAULT 'Pending';

-- 3. SEED DATA: fresh stock for all 14 venues
INSERT INTO inventory (id, venue, count, label)
VALUES 
  -- Existing Venues
  ('duffle_bag', 'Le Méridien Airport', 100, 'Heineken Bag'),
  ('laptop_bag', 'Le Méridien Airport', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Le Méridien Airport', 20, 'Laptop Sleeve'),
  ('try_again', 'Le Méridien Airport', 200, 'Try Again'),
  ('duffle_bag', 'Buffalo Wings & Rings', 100, 'Heineken Bag'),
  ('laptop_bag', 'Buffalo Wings & Rings', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Buffalo Wings & Rings', 20, 'Laptop Sleeve'),
  ('try_again', 'Buffalo Wings & Rings', 200, 'Try Again'),
  ('duffle_bag', 'The Villa Hub', 100, 'Heineken Bag'),
  ('laptop_bag', 'The Villa Hub', 50, 'Laptop Case'),
  ('laptop_sleeve', 'The Villa Hub', 20, 'Laptop Sleeve'),
  ('try_again', 'The Villa Hub', 200, 'Try Again'),
  -- New Venues
  ('duffle_bag', 'JW Marriott Mirage - Plato', 100, 'Heineken Bag'),
  ('laptop_bag', 'JW Marriott Mirage - Plato', 50, 'Laptop Case'),
  ('laptop_sleeve', 'JW Marriott Mirage - Plato', 20, 'Laptop Sleeve'),
  ('try_again', 'JW Marriott Mirage - Plato', 200, 'Try Again'),
  ('duffle_bag', 'Westin Dunes', 100, 'Heineken Bag'),
  ('laptop_bag', 'Westin Dunes', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Westin Dunes', 20, 'Laptop Sleeve'),
  ('try_again', 'Westin Dunes', 200, 'Try Again'),
  ('duffle_bag', 'The Tap East', 100, 'Heineken Bag'),
  ('laptop_bag', 'The Tap East', 50, 'Laptop Case'),
  ('laptop_sleeve', 'The Tap East', 20, 'Laptop Sleeve'),
  ('try_again', 'The Tap East', 200, 'Try Again'),
  ('duffle_bag', 'Amici West', 100, 'Heineken Bag'),
  ('laptop_bag', 'Amici West', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Amici West', 20, 'Laptop Sleeve'),
  ('try_again', 'Amici West', 200, 'Try Again'),
  ('duffle_bag', 'Tipsy Camel', 100, 'Heineken Bag'),
  ('laptop_bag', 'Tipsy Camel', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Tipsy Camel', 20, 'Laptop Sleeve'),
  ('try_again', 'Tipsy Camel', 200, 'Try Again'),
  ('duffle_bag', 'Zouni El Gouna', 100, 'Heineken Bag'),
  ('laptop_bag', 'Zouni El Gouna', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Zouni El Gouna', 20, 'Laptop Sleeve'),
  ('try_again', 'Zouni El Gouna', 200, 'Try Again'),
  ('duffle_bag', 'Rush El Gouna', 100, 'Heineken Bag'),
  ('laptop_bag', 'Rush El Gouna', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Rush El Gouna', 20, 'Laptop Sleeve'),
  ('try_again', 'Rush El Gouna', 200, 'Try Again'),
  ('duffle_bag', 'Chez Guevara Hurghada', 100, 'Heineken Bag'),
  ('laptop_bag', 'Chez Guevara Hurghada', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Chez Guevara Hurghada', 20, 'Laptop Sleeve'),
  ('try_again', 'Chez Guevara Hurghada', 200, 'Try Again'),
  ('duffle_bag', 'Las Vegas Hurghada', 100, 'Heineken Bag'),
  ('laptop_bag', 'Las Vegas Hurghada', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Las Vegas Hurghada', 20, 'Laptop Sleeve'),
  ('try_again', 'Las Vegas Hurghada', 200, 'Try Again'),
  ('duffle_bag', 'London Bridge Hurghada', 100, 'Heineken Bag'),
  ('laptop_bag', 'London Bridge Hurghada', 50, 'Laptop Case'),
  ('laptop_sleeve', 'London Bridge Hurghada', 20, 'Laptop Sleeve'),
  ('try_again', 'London Bridge Hurghada', 200, 'Try Again'),
  ('duffle_bag', 'Waves Hurghada', 100, 'Heineken Bag'),
  ('laptop_bag', 'Waves Hurghada', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Waves Hurghada', 20, 'Laptop Sleeve'),
  ('try_again', 'Waves Hurghada', 200, 'Try Again'),
  -- More New Venues
  ('duffle_bag', 'Andiamo', 100, 'Heineken Bag'),
  ('laptop_bag', 'Andiamo', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Andiamo', 20, 'Laptop Sleeve'),
  ('try_again', 'Andiamo', 200, 'Try Again'),
  ('duffle_bag', 'Amici New Giza', 100, 'Heineken Bag'),
  ('laptop_bag', 'Amici New Giza', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Amici New Giza', 20, 'Laptop Sleeve'),
  ('try_again', 'Amici New Giza', 200, 'Try Again'),
  ('duffle_bag', 'Tap West', 100, 'Heineken Bag'),
  ('laptop_bag', 'Tap West', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Tap West', 20, 'Laptop Sleeve'),
  ('try_again', 'Tap West', 200, 'Try Again'),
  -- Added Venues
  ('duffle_bag', 'Amici Play', 100, 'Heineken Bag'),
  ('laptop_bag', 'Amici Play', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Amici Play', 20, 'Laptop Sleeve'),
  ('try_again', 'Amici Play', 200, 'Try Again'),
  ('duffle_bag', 'Il Punto', 100, 'Heineken Bag'),
  ('laptop_bag', 'Il Punto', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Il Punto', 20, 'Laptop Sleeve'),
  ('try_again', 'Il Punto', 200, 'Try Again'),
  ('duffle_bag', 'L''Apero', 100, 'Heineken Bag'),
  ('laptop_bag', 'L''Apero', 50, 'Laptop Case'),
  ('laptop_sleeve', 'L''Apero', 20, 'Laptop Sleeve'),
  ('try_again', 'L''Apero', 200, 'Try Again'),
  ('duffle_bag', 'Queen Vic', 100, 'Heineken Bag'),
  ('laptop_bag', 'Queen Vic', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Queen Vic', 20, 'Laptop Sleeve'),
  ('try_again', 'Queen Vic', 200, 'Try Again'),
  ('duffle_bag', 'Hard Rock Nabq', 100, 'Heineken Bag'),
  ('laptop_bag', 'Hard Rock Nabq', 50, 'Laptop Case'),
  ('laptop_sleeve', 'Hard Rock Nabq', 20, 'Laptop Sleeve'),
  ('try_again', 'Hard Rock Nabq', 200, 'Try Again')
ON CONFLICT (id, venue) DO NOTHING;

-- 4. ENABLE SECURITY (RLS)
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read/update inventory (for game logic)
CREATE POLICY "inventory_public_access" ON inventory FOR ALL USING (true) WITH CHECK (true);

-- Allow anyone to insert/read leads (for registration and admin)
CREATE POLICY "leads_public_access" ON leads FOR ALL USING (true) WITH CHECK (true);


-- 5. ATOMIC INVENTORY DECREMENT FUNCTION
-- This ensures stock is reduced correctly even if multiple people win at once
CREATE OR REPLACE FUNCTION decrement_inventory(p_id TEXT, p_venue TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE inventory
  SET count = count - 1
  WHERE id = p_id AND venue = p_venue AND count > 0;
END;
$$ LANGUAGE plpgsql;

