-- SQL to set up the UCL Slot Game database

-- 1. Create the inventory table
CREATE TABLE IF NOT EXISTS inventory (
  id TEXT PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0,
  label TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the leads table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  prize TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insert initial inventory data
INSERT INTO inventory (id, count, label)
VALUES 
  ('duffle_bag', 100, 'Heineken Bag'),
  ('laptop_bag', 50, 'Laptop Case'),
  ('laptop_sleeve', 20, 'Laptop Sleeve'),
  ('try_again', 200, 'Try Again')
ON CONFLICT (id) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- 5. Create policies (Allow anon access for this specific app's needs)
-- Note: In a production app, you might want more restrictive policies.
CREATE POLICY "Enable read for all users" ON inventory FOR SELECT USING (true);
CREATE POLICY "Enable update for all users" ON inventory FOR UPDATE USING (true);
CREATE POLICY "Enable insert for all users" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all users" ON leads FOR SELECT USING (true);
CREATE POLICY "Enable update for all users" ON leads FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON leads FOR DELETE USING (true);
